// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: protocol/pb/envelope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the binary transport wrapper. Payload remains a JSON message
// during the compatibility migration; defining it as bytes lets old typed
// payload validation remain authoritative while clients negotiate protobuf
// framing independently.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protocol_pb_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protocol_pb_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_protocol_pb_envelope_proto protoreflect.FileDescriptor

const file_protocol_pb_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1aprotocol/pb/envelope.proto\x12\x11chess.protocol.v1\"q\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\x19Z\x17chess-go/protocol/pb;pbb\x06proto3"

var (
	file_protocol_pb_envelope_proto_rawDescOnce sync.Once
	file_protocol_pb_envelope_proto_rawDescData []byte
)

func file_protocol_pb_envelope_proto_rawDescGZIP() []byte {
	file_protocol_pb_envelope_proto_rawDescOnce.Do(func() {
		file_protocol_pb_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_pb_envelope_proto_rawDesc), len(file_protocol_pb_envelope_proto_rawDesc)))
	})
	return file_protocol_pb_envelope_proto_rawDescData
}

var file_protocol_pb_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_pb_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: chess.protocol.v1.Envelope
}
var file_protocol_pb_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_pb_envelope_proto_init() }
func file_protocol_pb_envelope_proto_init() {
	if File_protocol_pb_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_pb_envelope_proto_rawDesc), len(file_protocol_pb_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_pb_envelope_proto_goTypes,
		DependencyIndexes: file_protocol_pb_envelope_proto_depIdxs,
		MessageInfos:      file_protocol_pb_envelope_proto_msgTypes,
	}.Build()
	File_protocol_pb_envelope_proto = out.File
	file_protocol_pb_envelope_proto_goTypes = nil
	file_protocol_pb_envelope_proto_depIdxs = nil
}
